// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7Cr0HDCntujbYYVopy3zbRrZaH8dPNA',
    appId: '1:937563599774:web:798299dcfe8c8fd103dc8f',
    messagingSenderId: '937563599774',
    projectId: 'bean-model',
    authDomain: 'bean-model.firebaseapp.com',
    storageBucket: 'bean-model.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGtDWXWxPHc2pteTyUq82Ybd6vH_79b8g',
    appId: '1:937563599774:android:dc0c6994b3e9784a03dc8f',
    messagingSenderId: '937563599774',
    projectId: 'bean-model',
    storageBucket: 'bean-model.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN46CYQ2WSm1vCctztWPQCskMXUV-xto0',
    appId: '1:937563599774:ios:b11e5536556080ce03dc8f',
    messagingSenderId: '937563599774',
    projectId: 'bean-model',
    storageBucket: 'bean-model.firebasestorage.app',
    iosBundleId: 'com.example.beanModel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN46CYQ2WSm1vCctztWPQCskMXUV-xto0',
    appId: '1:937563599774:ios:b11e5536556080ce03dc8f',
    messagingSenderId: '937563599774',
    projectId: 'bean-model',
    storageBucket: 'bean-model.firebasestorage.app',
    iosBundleId: 'com.example.beanModel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy7Cr0HDCntujbYYVopy3zbRrZaH8dPNA',
    appId: '1:937563599774:web:c36273a3e56b830f03dc8f',
    messagingSenderId: '937563599774',
    projectId: 'bean-model',
    authDomain: 'bean-model.firebaseapp.com',
    storageBucket: 'bean-model.firebasestorage.app',
  );
}
